site_name: documentations-lite-llm
site_description: documentations-lite-llm

nav:
  - Home: index.md
  - Overview:
      - What's New: overview/whats-new.md
      - Roadmap: overview/roadmap.md
      - Architecture: overview/architecture.md
      - Database: overview/database.md
      - Metrics: overview/metrics.md
      - Key Features: overview/key-features.md
  - Getting Started:
      - Prerequisites: getting-started/prerequisites.md
      - Installation: getting-started/installation.md
      - Deployment: getting-started/deployment.md
  - User Guide:
      - Configuration: user-guide/configuration.md
      - How to Use: user-guide/how-to-use.md
  - Operations:
      - Testing: operations/testing.md
      - Troubleshooting: operations/troubleshooting.md
      - FAQ: operations/faq.md
  - Glossary: glossary.md
  - Reference: reference.md

theme:
  name: material

plugins:
  - techdocs-core
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - attr_list
  - md_in_html

extra_css:
  - stylesheets/extra.css 
